server:
  port: 8020
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beetl?useSSL=false
    username: root
    password: '!Qaz2wsx'
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    timeBetweenEvictionRunsMillis: 60000